# Generated by Django 5.2.4 on 2025-08-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
