# Generated by Django 5.2.4 on 2025-08-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_teacher_invitations_alter_student_is_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher_invitations',
            new_name='invitations',
        ),
        migrations.AddField(
            model_name='teacher',
            name='invitations',
            field=models.ManyToManyField(related_name='teacher_invitations', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
