# Generated by Django 5.2.4 on 2025-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_concluded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_to_display', models.CharField(blank=True, max_length=200, null=True)),
                ('composer', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=60, null=True)),
                ('opus', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('genre', models.CharField(blank=True, max_length=60, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('pitch', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=70, null=True)),
                ('time_to_master', models.DurationField(blank=True, help_text='Sugerowany czas opanowania utworu', null=True)),
                ('is_mastered', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('goal', models.ManyToManyField(blank=True, null=True, to='tracker.goal')),
            ],
        ),
    ]
