# Generated by Django 5.2.4 on 2025-08-22 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_challenge_minimum_number_of_repetitions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='pieceinformation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='style',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='type',
            name='pieces',
        ),
        migrations.AddField(
            model_name='genre',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pieceinformation',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='pieces_information', to='tracker.genre'),
        ),
        migrations.AddField(
            model_name='pieceinformation',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='pieces_information', to='tracker.style'),
        ),
        migrations.AddField(
            model_name='pieceinformation',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='pieces_information', to='tracker.type'),
        ),
        migrations.AddField(
            model_name='style',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pieceinformation',
            name='piece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piece_information', to='tracker.piece'),
        ),
    ]
