# Generated by Django 5.2.4 on 2025-08-24 17:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_genre_pieces_remove_pieceinformation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='tasks',
        ),
        migrations.AddField(
            model_name='challenge',
            name='are_minimum_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 8, 24, 17, 52, 6, 687863, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tracker.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='is_summarized',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='suggest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_suggested',
            field=models.BooleanField(default=True),
        ),
    ]
