# Generated by Django 5.2.4 on 2025-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_challenge_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='was_practiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
