# Generated by Django 5.2.4 on 2025-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_task_was_practiced_alter_challenge_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='are_minimum_fulfilled',
            new_name='are_requirements_fulfilled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='suggest',
        ),
        migrations.AddField(
            model_name='task',
            name='are_suggestions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
