# Generated by Django 5.2.4 on 2025-08-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_are_minimum_fulfilled_challenge_are_requirements_fulfilled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='minimum_number_of_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='minimum_number_of_repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='minimum_total_repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
